# Generated by Django 3.0.3 on 2020-05-03 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=30, null=True)),
                ('rating', models.FloatField(blank=True, max_length=4, null=True)),
                ('html', models.FileField(blank=True, null=True, upload_to='media/html')),
                ('css', models.FileField(blank=True, null=True, upload_to='media/css')),
                ('js', models.FileField(blank=True, null=True, upload_to='media/js')),
            ],
        ),
        migrations.CreateModel(
            name='CardModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=30, null=True)),
                ('rating', models.FloatField(blank=True, max_length=4, null=True)),
                ('html', models.FileField(blank=True, null=True, upload_to='media/html')),
                ('css', models.FileField(blank=True, null=True, upload_to='media/css')),
                ('js', models.FileField(blank=True, null=True, upload_to='media/js')),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('But', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.ButtonModel')),
                ('Card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.CardModel')),
            ],
        ),
    ]
