# Generated by Django 3.0.5 on 2020-05-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buttonmodel',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='buttonmodel',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='media/preview'),
        ),
    ]
