# Generated by Django 3.0.4 on 2020-04-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('button_id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(default='a', unique=True)),
                ('upload', models.FileField(blank=True, upload_to='buttons/')),
                ('title', models.CharField(default='button', max_length=100)),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
